// -*- Protocol-Buffers -*-
//==============================================================================
/// @file relay_service.proto
/// @brief Pub/Sub Relay gRPC interface
/// @author Tor Slettnes
//==============================================================================

syntax = "proto3";

package cc.platform.pubsub.grpc;

import "google/protobuf/empty.proto";
import "cc/platform/pubsub/protobuf/pubsub_types.proto";

service Relay
{
    // Set custom replay policies on the specified topics
    // If no topics are listed, obtain all replay policies.
    rpc AssignReplayPolicies (pubsub.protobuf.ReplayPolicyMap)
        returns (google.protobuf.Empty);

    // Remove custom replay policies on the specified topics.
    // If no topics are listed, remove all replay policies.
    rpc UnassignReplayPolicies (pubsub.protobuf.Topics)
        returns (google.protobuf.Empty);

    // List replay policies currently in effect on the specified topics.
    // If no topics are given, list all current replay policies.
    rpc GetReplayPolicies (pubsub.protobuf.Topics)
        returns (pubsub.protobuf.ReplayPolicyMap);

    // Write/publish a stream of messages to pubsub.
    rpc Publisher (stream pubsub.protobuf.Publication)
        returns (google.protobuf.Empty);

    // Publish a single message to pubsub.
    rpc Publish (pubsub.protobuf.Publication)
        returns (google.protobuf.Empty);

    // Read/subscribe to messages from broker.
    rpc Subscriber (pubsub.protobuf.Filters)
        returns (stream pubsub.protobuf.Publication);

}
