// -*- Protocol-Buffers -*-
//==============================================================================
/// @file pubsub_types.proto
/// @brief Pub/Sub data types
/// @author Tor Slettnes
//==============================================================================

syntax = "proto3";

package cc.platform.pubsub.protobuf;

import "cc/protobuf/variant/variant.proto";

message Publication
{
    // Message topic
    string topic = 2;

    // Payload.
    cc.protobuf.variant.Value value = 15;
}

message Topics
{
    repeated string topics = 2;
}

message Filters
{
    // Zero or more message filters.  A subscription request with no filters
    // will match all messages.
    repeated string topics = 2;

    // Subscriber-side replay control.
    ReplayControl replay = 8;
}


enum ReplayControl
{
    REPLAY_DEFAULT = 0;         // Stream replay cache, then live publications
    REPLAY_OFF     = 1;         // Skip replay, stream only live publications
    REPLAY_ONLY    = 2;         // Replay cached publications, then close stream
}


message ReplayPolicyMap
{
    map<string, ReplayPolicy> map = 2;
}

message ReplayPolicy
{
    // Cache and replay the latest publication(s) on this topic to future
    // subscribers. Multiple messages may be replayed if one or more
    // `key_paths` are provided, below.
    optional bool replay_latest = 8;

    // A sequence of hierachical paths to nested values expected to be present
    // in subsequently published key/value payloads. These corresponding values
    // are then combined into a mapping key, by which the message is mapped and
    // retained in the server's replay cache.
    //
    // In other words, at any point in time the relay retains a snapshot of the
    // latest publication for each unique combination of values extracted from
    // these key paths.
    //
    // Subsequently, whenever a Subscriber() call is initiated by a client, this
    // snapshot of publications is immediately streamed back from the replay
    // cache, after which real-time streaming of live publications starts.
    repeated KeyPath key_paths = 10;
}

message KeyPath
{
    // Elements that form a hierachical path to values within published
    // messages.  Elements leading up to the final one are expected to reference
    // nested key/value maps, and the final element should refer to a value
    // suitable as a mapping key (typically a string).
    repeated string elements = 2;
}
