// -*- Protocol-Buffers -*-
//==============================================================================
/// @file relay.proto
/// @brief Relay gRPC interface
/// @author Tor Slettnes
//==============================================================================

syntax = "proto3";

package cc.platform.relay.grpc;

import "google/protobuf/empty.proto";
import "cc/platform/relay/protobuf/relay_types.proto";

service Relay
{
    // Read/subscribe to messages from broker.
    rpc Reader (relay.protobuf.Filters)
        returns (stream relay.protobuf.Message);

    // Write/publish to messages to relay.
    rpc Writer (stream relay.protobuf.Message)
        returns (google.protobuf.Empty);
}

